from odoo import api, fields, models


class ObstetricFollowUp(models.Model):
    _name = 'obstetric.follow.up'
    _description = 'Obstetric Follow-up'
    _rec_name = 'patient_id'

    patient_id = fields.Many2one(
        comodel_name='res.partner',
        string='Patient',
        required=False)

    date_1st_trimester = fields.Date(
        string='Date',
        required=False)

    g_1 = fields.Char(
        string='G',
        required=False)
    p_1 = fields.Char(
        string='P',
        required=False)
    c_1 = fields.Char(
        string='C',
        required=False)
    a_1 = fields.Char(
        string='A',
        required=False)
    ddr = fields.Date(
        string='DDR',
        required=False)
    dpr = fields.Date(
        string='DPA',
        required=False)
    ac = fields.Boolean(
        string='AC',
        required=False)
    vv = fields.Boolean(
        string='VV',
        required=False)
    lcc = fields.Boolean(
        string='LCC',
        required=False)
    cn = fields.Boolean(
        string='CN',
        required=False)
    pole_cephalique = fields.Boolean(
        string='Pole céphalique',
        required=False)
    membre_4 = fields.Boolean(
        string='4 membres + 3 segments',
        required=False)
    trophoblaste = fields.Boolean(
        string='Trophoblaste',
        required=False)
    maf = fields.Boolean(
        string='MAF',
        required=False)
    conclusion_1 = fields.Text(
        string="Conclusion",
        sanitize_style=True,
        required=False)

    date_2nd_trimester = fields.Date(
        string='Date',
        required=False)
    grossesse_2 = fields.Char(
        string='Grossesse',
        required=False)

    ac_2 = fields.Char(
        string='AC',
        required=False)
    maf_2 = fields.Char(
        string='MAF',
        required=False)
    bip_2 = fields.Char(
        string='BIP',
        required=False)
    femur_2 = fields.Char(
        string='FEMEUR',
        required=False)
    poids_2 = fields.Float(
        string='Poids',
        required=False)
    face_2 = fields.Boolean(
        string='FACE',
        required=False)
    estomac_2 = fields.Boolean(
        string='Estomac',
        required=False)
    rachis_2 = fields.Boolean(
        string='Rachis',
        required=False)
    liquide_amni_2 = fields.Boolean(
        string='Liquide amniotique',
        required=False)
    placenta_2 = fields.Boolean(
        string='Placenta',
        required=False)
    hearth_2 = fields.Boolean(
        string='Coeur et vx',
        required=False)
    membres_2 = fields.Boolean(
        string='Membres', 
        required=False)
    reins_2 = fields.Boolean(
        string='Reins et vessie',
        required=False)
    presentation_2 = fields.Html(
        string="Presentation",
        required=False)
    conclusion_2 = fields.Html(
        string="Conclusion",
        sanitize_style=True,
        required=False)

    date_3nd_trimester = fields.Date(
        string='Date',
        required=False)
    grossesse_3 = fields.Char(
        string='Grossesse',
        required=False)

    ac_3 = fields.Char(
        string='AC',
        required=False)
    maf_3 = fields.Char(
        string='MAF',
        required=False)
    bip_3 = fields.Char(
        string='BIP',
        required=False)
    femur_3 = fields.Char(
        string='FEMEUR',
        required=False)
    poids_3 = fields.Float(
        string='Poids',
        required=False)
    face_3 = fields.Boolean(
        string='FACE',
        required=False)
    estomac_3 = fields.Boolean(
        string='Estomac',
        required=False)
    rachis_3 = fields.Boolean(
        string='Rachis',
        required=False)
    liquide_amni_3 = fields.Boolean(
        string='Liquide amniotique',
        required=False)
    placenta_3 = fields.Boolean(
        string='Placenta',
        required=False)
    hearth_3 = fields.Boolean(
        string='Coeur et vx',
        required=False)
    membres_3 = fields.Boolean(
        string='Membres',
        required=False)
    reins_3 = fields.Boolean(
        string='Reins et vessie',
        required=False)
    presentation_3 = fields.Html(
        string="Presentation",
        required=False)
    conclusion_3 = fields.Html(
        string="Conclusion",
        sanitize_style=True,
        required=False)

    state = fields.Selection(
        string='State',
        selection=[('current', 'En cours'),
                   ('ended', 'Terminé'), ],
        default="current",
        required=False, )


